# Generated by Django 5.1.1 on 2024-11-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0004_otc_bond_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='otc_bond_holding',
            name='price_per_10',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otc_bond_holding',
            name='purchase_date',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otc_bond_holding',
            name='quantity',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
