# Generated by Django 5.1.1 on 2024-11-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0005_otc_bond_holding_price_per_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otc_bond_holding',
            name='expire_date',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
