# Generated by Django 5.1.1 on 2024-11-02 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0006_otc_bond_holding_expire_date'),
        ('crawling', '0006_otc_bond_holding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc_bond_holding',
            name='bond_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_bonds', to='crawling.otc_bond'),
        ),
        migrations.AlterField(
            model_name='otc_bond_holding',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_bonds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='otc_bond_holding',
            table='OTC_Bond_Holding',
        ),
    ]
