# Generated by Django 5.1.1 on 2024-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0007_alter_otc_bond_holding_bond_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc_bond_holding',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
