# Generated by Django 5.1.1 on 2024-11-02 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0008_alter_otc_bond_holding_expire_date'),
        ('crawling', '0009_alter_otc_bond_expired_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTC_Bond_Expired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_bonds', to='crawling.otc_bond')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_bonds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OTC_Bond_Expired',
            },
        ),
    ]
