# Generated by Django 5.1.1 on 2024-11-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0009_otc_bond_expired'),
        ('crawling', '0010_otcbondpredata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtcBondPreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_data_set', to='crawling.otc_bond')),
            ],
            options={
                'db_table': 'OtcBondPreData',
            },
        ),
    ]
