# Generated by Django 5.1.1 on 2024-11-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0010_otcbondpredata'),
        ('crawling', '0011_otcbondpredatadays_delete_otcbondpredata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtcBondPreData',
            new_name='OtcBondPreDataDays',
        ),
    ]
