# Generated by Django 5.1.1 on 2024-11-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0011_rename_otcbondpredata_otcbondpredatadays'),
        ('crawling', '0012_otcbondpredatamonths_otcbondpredataweeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtcBondPreDataMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_data_months_set', to='crawling.otc_bond')),
            ],
            options={
                'db_table': 'OtcBondPreDataMonths',
            },
        ),
        migrations.CreateModel(
            name='OtcBondPreDataWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_data_weeks_set', to='crawling.otc_bond')),
            ],
            options={
                'db_table': 'OtcBondPreDataWeeks',
            },
        ),
    ]
