# Generated by Django 5.1.1 on 2024-10-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otc_bond",
            name="id",
        ),
        migrations.AlterField(
            model_name="otc_bond",
            name="bond_code",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
