# Generated by Django 5.1.1 on 2024-10-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0002_remove_otc_bond_id_alter_otc_bond_bond_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otc_bond",
            old_name="bond_name",
            new_name="bond_int_dfrm_mthd_cd",
        ),
        migrations.RenameField(
            model_name="otc_bond",
            old_name="bond_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="otc_bond",
            old_name="bond_type",
            new_name="expd_dt",
        ),
        migrations.RenameField(
            model_name="otc_bond",
            old_name="danger_degree",
            new_name="issu_dt",
        ),
        migrations.RenameField(
            model_name="otc_bond",
            old_name="int_pay_class",
            new_name="issu_istt_name",
        ),
        migrations.RenameField(
            model_name="otc_bond",
            old_name="mat_date",
            new_name="nice_crdt_grad_text",
        ),
        migrations.RenameField(
            model_name="otc_bond",
            old_name="nxt_int_date",
            new_name="nxtm_int_dfrm_dt",
        ),
        migrations.RenameField(
            model_name="otc_bond",
            old_name="pub_date",
            new_name="prdt_name",
        ),
        migrations.RenameField(
            model_name="otc_bond",
            old_name="trading_company_name",
            new_name="prdt_type_cd",
        ),
    ]
