# Generated by Django 5.1.1 on 2024-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0005_remove_otc_bond_adddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTC_Bond_Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_10', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('purchase_date', models.CharField(max_length=100)),
                ('expire_date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OTC_Bond_Holding',
                'managed': False,
            },
        ),
    ]
