# Generated by Django 5.1.1 on 2024-11-02 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0006_otc_bond_holding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="otc_bond",
            name="add_date",
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OTC_Bond_Expired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bond_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawling.otc_bond",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
