# Generated by Django 5.1.1 on 2024-11-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0007_otc_bond_add_date_otc_bond_expired"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="otc_bond_expired",
            table="OTC_Bond_Expired",
        ),
    ]
