# Generated by Django 5.1.1 on 2024-11-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0011_otcbondpredatadays_delete_otcbondpredata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtcBondPreDataMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OtcBondPreDataMonths',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtcBondPreDataWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OtcBondPreDataWeeks',
                'managed': False,
            },
        ),
    ]
