# Generated by Django 5.1.1 on 2024-10-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketbond", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="marketbondinquiredailyitemchartprice",
            name="unique_daily_item_chart_price",
        ),
        migrations.AddConstraint(
            model_name="marketbondinquiredailyitemchartprice",
            constraint=models.UniqueConstraint(
                fields=("stck_bsop_date", "code"), name="unique_daily_item_chart_price"
            ),
        ),
    ]
